name: New Release

on:
  push: 
    branches: [main]

permissions:
  contents: write
  discussions: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git configuration
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"  

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          path: | 
            ~/.npm
            ./node_modules

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build:production

      - name: Create Npm Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public --userconfig 
        

          
