name: New Release

on:
  push: 
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          path: | 
            ~/.npm
            ./node_modules

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build:production

      - name: Create Release Publish to npm
        uses: changesets/action@v1
        with:
          commit: "🎉 new release version"
          title: "🎉 new release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
