name: New Release

on:
  push: 
    branches: [main]
    paths-ignore: 
      - "**/*.md"
      - "LISCENSE"
      - ".gitignore"
      - ".eslintrs.js"
      - ".eslintignore"
      - "**/*.cy.ts"
      - "**/*.test.ts"
      - "./jest.config.js"
      - "./cypress.config.ts"

permissions:
  contents: write
  discussions: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git configuration
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"  

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          path: | 
            ~/.npm
            ./node_modules

      - name: Get package version
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "Package version is $PACKAGE_VERSION"


      - name: Install dependencies
        run: npm ci
        
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: "SimpleMaskMoney - v${{ env.PACKAGE_VERSION }}"
          tag_name: "v${{ env.PACKAGE_VERSION }}"
          files: | 
            package.json
            package-lock.json
            lib/*
            lib/types.d.ts
            lib/create-instance-of.d.ts 
            lib/create-instance-of.cjs.js
            lib/create-instance-of.esm.js 
            lib/create-instance-of.umd.js 
            lib/create-instance-of.cjs.js.map 
            lib/create-instance-of.esm.js.map
            lib/create-instance-of.umd.js.map 
            lib/format-to-currency.d.ts
            lib/format-to-currency.cjs.js
            lib/format-to-currency.esm.js
            lib/format-to-currency.umd.js
            lib/format-to-currency.cjs.js.map
            lib/format-to-currency.esm.js.map
            lib/format-to-currency.umd.js.map
            lib/format-to-number.d.ts
            lib/format-to-number.cjs.js
            lib/format-to-number.esm.js
            lib/format-to-number.umd.js
            lib/format-to-number.cjs.js.map
            lib/format-to-number.esm.js.map
            lib/format-to-number.umd.js.map
            lib/get-base-configuration.d.ts
            lib/remove-mask.d.ts
            lib/remove-mask.cjs.js
            lib/remove-mask.esm.js
            lib/remove-mask.umd.js
            lib/remove-mask.cjs.js.map
            lib/remove-mask.esm.js.map
            lib/remove-mask.umd.js.map
            lib/set-mask.d.ts
            lib/set-mask.cjs.js
            lib/set-mask.esm.js
            lib/set-mask.umd.js
            lib/set-mask.cjs.js.map
            lib/set-mask.esm.js.map
            lib/set-mask.umd.js.map
            lib/simple-mask-money.d.ts
            lib/simple-mask-money.cjs.js
            lib/simple-mask-money.esm.js
            lib/simple-mask-money.umd.js
            lib/simple-mask-money.cjs.js.map
            lib/simple-mask-money.esm.js.map
            lib/simple-mask-money.umd.js.map

      - name: Build package
        run: npm run build:production

      - name: Create Npm Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public --userconfig ./.npmrc
        

          
