name: Pull Request

on:
  pull_request:
    branches-ignore: |
      **/*.md
      docs/**/*
      examples/**/*

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          path: | 
            ~/.npm
            ./node_modules

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build:production

      - name: Run unit test
        run: npm run test

      - name: Run e2e test
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
